---

clion_version: 2023.1
clion_download_mirror: https://download.jetbrains.com/cpp/
clion_download_directory: /tmp
clion_user_dir: "{{ ansible_env.HOME }}"
clion_install_directory: "{{ clion_user_dir | expanduser }}"

clion_install_file: "CLion-{{ clion_version }}.tar.gz"
clion_download_url: "{{ clion_download_mirror }}{{ clion_install_file }}"
clion_location: "{{ clion_install_directory }}/clion-{{ clion_version }}"
